### ISSUE TITLE
DSL2 Module Versioning

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#1112]
Large overview issue to track progress.

- [x] Update `nf-core modules install` to create / edit a `modules.json` in the root - #868
- [x] Update `nf-core modules lint` to check the specific git commit - #1114 
- [x] Check that `nf-core modules lint` works with `modules.json` when checking for new versions - #1114 
- [x] Update `nf-core modules remove` to update `modules.json` - #1115 
- [x] Create `nf-core modules update` - #1111
- [x] Update `nf-core modules list` - more meta, show versions for a specific tool

**Comment by KevinMenden** [comment]
Closing this as all major functionality has now been implemented in `dev`
What remains is testing, debugging and making adjustments where needed over time.
