### ISSUE TITLE
Replace params.modules with PublishDir and process.ext settings. 

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/tools#1283]
# nf-core/tools feature request

This issue is a collection point for discussions on various topics regarding https://github.com/nf-core/rnaseq/pull/701.

## Is your feature request related to a problem? Please describe

PublishDir and tool arg configuration is distributed in many places in the nf-core workflows. 
Using publishDir and process selectors could remedy file publishing configuration to be in one place.
Using ext.args and process selectors could provide tool parameters configuration in one place. 

## Describe the solution you'd like

https://github.com/nf-core/rnaseq/pull/701 shows it implemented in the nf-core rnaseq workflow. 

## Current discussion points:

- Using custom functions in `nextflow.config`: https://github.com/nf-core/rnaseq/pull/701#discussion_r725945757
- How to proceed with ext.args changes not triggering reruns:https://github.com/nf-core/rnaseq/pull/701#discussion_r725950463 
- How to lint `publishDir` directives: https://github.com/nf-core/rnaseq/pull/701#discussion_r725958319 

## TODO list

- [ ] Updating nf-core/modules
- [ ] Update module template 
- [ ] Update pipeline template, 
- [ ] lib/ (if keeping `getSoftwareName`, `getProcessName`). 
- [ ] Update linter to check for `mode: params.publish_dir_mode`. 
- [ ] Update linter to check for `enabled:false`, `pattern: `, or `saveAs: { filename -> filename.equals('versions.yml') ? null : filename }`
- [ ] Update tests to use `publishDir` in config and remove `NF_CORE_MODULES_TEST=1` env.
