### ISSUE TITLE
[UPDATE] TODO list for new DSL2 syntax

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1334]
## Pipeline template

- [x] Update modules in pipeline template from nf-core/modules
    - [x] Check MultiQC output of `custom/dumpsoftwareversions` after updating from nf-core/modules
    - [x] Check `modules.json` is formatted properly after updating modules
- [x] Remove `params.publish_dir_mode` from pipeline template
- [x] Double-check #fetchngs conversion PR for updates to the pipeline template https://github.com/nf-core/fetchngs/pull/52
- [x] Bump min NF version in pipeline template to 21.10.3 as a result of changes required to adopt new syntax
- [x] Update Github Actions in pipeline template to use latest stable and edge version of NF

## Main tools repo

- [ ] Update CHANGELOG
- [x] Fix and test linting on a pipeline using old DSL2 syntax
- [x] Add functionality to install `templates` folder along with any modules if it exists https://github.com/drpatelh/nf-core-modules/pull/6

## Docs

- [ ] Add docs about globbing using process selectors in `modules.config`

**Comment by JoseEspinosa** [comment]
I added an item: 
`- [ ] Update modules in pipeline template from nf-core/modules`
