### ISSUE TITLE
pathlib adoption roadmap and summary issue

### ISSUE THREAD

**Issue by fabianegli** [nf-core/tools#1703]
### Description of feature

PR #1700 grew too big and this is now an issue collecting the information about the adoption to pathlib.

- [ ] nf-core tools
- [ ] nf-core list
- [ ] nf-core launch
- [ ] nf-core download
- [ ] nf-core licences
- [ ] nf-core create
- [ ] nf-core lint
- [ ] nf-core schema
- [ ] nf-core bump-version
- [ ] nf-core syn
- [ ] nf-core module
    - [ ] modules lis
    - [ ] modules list remot
    - [ ] modules list loca
    - [ ] modules instal
    - [ ] modules updat
    - [ ] modules remov
    - [ ] modules creat
    - [ ] modules create-test-ym
    - [ ] modules lin
    - [ ] modules tes
    - [ ] modules bump-version
    - [ ] modules mulle
