### ISSUE TITLE
Modules meta.yml differentiate between tuple and single element channels

### ISSUE THREAD

**Issue by mirpedrol** [nf-core/tools#3248]
### Description of the bug

With the restructuring of the modules `meta.yml` files, we introduced an extra level of indentation to account for tuple channels. However, channels that are not tuples shouldn't be indented.

This must be fixed in:

- [ ] The module template
- [ ] When running `nf-core modules lint` with the `--fix` argument
- [ ] In the website when showing the inputs and outputs of modules
- [ ] The JSON schema from nf-core/modules must be updated
- [ ] All modules `meta.yml` must be fixed (can be done with a bulk PR by running `nf-core modules lint --fix --all`)
