### ISSUE TITLE
Lint pipelines nextflow schema against the meta schema

### ISSUE THREAD

**Issue by mirpedrol** [nf-core/tools#3288]
### Description of feature

Lint pipelines parameters schema (`nextflow_schema.json`) against the [meta schema](https://github.com/nextflow-io/nf-schema/blob/master/parameters_meta_schema.json)

To lint all pipelines, we should work on these steps:

- [ ] Manual check of the meta schema to check we're not missing anything obvious
- [ ] Think about hosting a copy of the meta schema somewhere else (currently under the nf-schema repo)
- [ ] Test all / most nf-core pipelines locally to check for errors
- [ ] Write GitHub action CI for one or two pipelines
- [ ] Add CI to the template
